columns = ['data.economy.budget.date', 'data.economy.budget.expenditures.units',
           'data.economy.budget.expenditures.value', 'data.economy.budget.revenues.units',
           'data.economy.budget.revenues.value', 'data.economy.budget_surplus_or_deficit.date',
           'data.economy.budget_surplus_or_deficit.percent_of_gdp', 'data.economy.exports.partners.by_country',
           'data.economy.exports.partners.date', 'data.economy.gdp.composition.by_end_use.date',
           'data.economy.gdp.composition.by_end_use.end_uses.exports_of_goods_and_services.units',
           'data.economy.gdp.composition.by_end_use.end_uses.exports_of_goods_and_services.value',
           'data.economy.gdp.composition.by_end_use.end_uses.household_consumption.value',
           'data.economy.household_income_by_percentage_share.highest_ten_percent.units',
           'data.economy.household_income_by_percentage_share.highest_ten_percent.value',
           'data.economy.household_income_by_percentage_share.lowest_ten_percent.units',
           'data.economy.household_income_by_percentage_share.lowest_ten_percent.value',
           'data.economy.industrial_production_growth_rate.annual_percentage_increase',
           'data.economy.industrial_production_growth_rate.date', 'data.energy.electricity.access.date',
           'data.energy.electricity.access.total_electrification.value',
           'data.energy.electricity.by_source.fossil_fuels.date',
           'data.energy.electricity.by_source.fossil_fuels.percent',
           'data.energy.electricity.by_source.hydroelectric_plants.date',
           'data.energy.electricity.by_source.hydroelectric_plants.percent',
           'data.energy.electricity.by_source.nuclear_fuels.date',
           'data.energy.electricity.by_source.nuclear_fuels.percent',
           'data.energy.electricity.by_source.other_renewable_sources.date',
           'data.energy.electricity.by_source.other_renewable_sources.percent']
